spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@webfluxcoursecluster.sneezho.mongodb.net/webflux-course?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: webflux-course